Jsx@2 app: upgrade script results
Error: This function has type
         {. "children": array(ReasonReact.reactElement), "id": string} 
=>
         React.element
       It is applied to too many arguments; maybe you forgot a `;'.